import type { Metadata } from "next";
import "./globals.css";
import NavBar from "@/components/global/Navbar/Navbar";
import { Roboto } from 'next/font/google'
import Footer from "@/components/global/Footer/Footer";
 
const roboto = Roboto({
  subsets:["latin"],
  weight:["100","300","400", "500","700", "900"]
})


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${roboto.className} antialiased`}
      >
        <NavBar/>
        {children}
        <Footer/>
      </body>
    </html>
  );
}
